// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaN9Esy5fs9G1fgplhzdLBU4YFGsipCDQ',
    appId: '1:266202752447:web:8b8bcd3c9b79333ec16d0a',
    messagingSenderId: '266202752447',
    projectId: 'metal-ad87d',
    authDomain: 'metal-ad87d.firebaseapp.com',
    storageBucket: 'metal-ad87d.appspot.com',
    measurementId: 'G-G1Z73JWRXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ky8QWCmHTDRa-gboNjwqIAvEiorvW7E',
    appId: '1:266202752447:android:fc7f82137ff3664dc16d0a',
    messagingSenderId: '266202752447',
    projectId: 'metal-ad87d',
    storageBucket: 'metal-ad87d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFGHwbJkOrpZ7R5bPsYc9T3tvtJn0FMR4',
    appId: '1:266202752447:ios:22ab4734ad166d45c16d0a',
    messagingSenderId: '266202752447',
    projectId: 'metal-ad87d',
    storageBucket: 'metal-ad87d.appspot.com',
    iosBundleId: 'com.bwh.metal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFGHwbJkOrpZ7R5bPsYc9T3tvtJn0FMR4',
    appId: '1:266202752447:ios:df65c41c1988ceb9c16d0a',
    messagingSenderId: '266202752447',
    projectId: 'metal-ad87d',
    storageBucket: 'metal-ad87d.appspot.com',
    iosBundleId: 'com.bwh.metal.RunnerTests',
  );
}
